### ISSUE TITLE
Extension created an infinite log that after a few hours of being open exceeded 100+gb

### ISSUE THREAD

**Issue by seppe-willems** [odoo/odoo-ls#95]
**Your setup**
Version: v0.2.2
Operating System: [Linux Mint 21.2 "Victoria"](https://www.linuxmint.com/edition.php?id=305)
IDE and/or Integration tool (for example: Vscode - official extension): 
vs code 

**Describe the bug**
![image](https://github.com/odoo/odoo-ls/assets/128471301/0e0ff2f0-0da9-4a52-b60f-541119b7b6bc)

**To Reproduce**
I had to tool open on a project for a few hours, in the background it was creating an infinite log, when I noticied it was 100+gb
**Expected behavior**
Dont take up 100gb on my system

**Screenshots**

**Comment by fda-odoo** [comment]
Hello @seppe-willems ,

Thank you for your report. This issue is already known and fixed in the last version of the tool (https://github.com/odoo/odoo-ls/pull/83), that should be deployed today. Let us know if you still face it in the future, but hopefully it should not !
You can of course safely delete the file without harming the extension ;)

**Comment by seppe-willems** [comment]
@fda-odoo 
I updated to the newest version
![image](https://github.com/odoo/odoo-ls/assets/128471301/fa150521-7a7c-4b27-9688-fd800ba752ce)
![image](https://github.com/odoo/odoo-ls/assets/128471301/6b547205-1a27-4d2a-9173-45e8500353bd)

And when the pipeline breaks it still creates a huge log, write about a 1gb in 2/3 minutes

**Comment by fda-odoo** [comment]
Ouch, this issue seems to want to stay !
It seems that the BrokenPipeError is catched by the PyGLS library, and that our fix is bypassed.
I'll create a PR asap
